version: "3.9"
services:
  api:
    container_name: node-starter
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:${REDIS_PORT}"
    volumes:
      - data:/data/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}
volumes:
  data: {}
